# Usa imagem oficial do Node 22
FROM node:22

# Entra de trabalho
WORKDIR /app

# Copia arquivos necessários para instalar as dependencia node_modules EM TEMPO DE BUILD
COPY package*.json ./
COPY worker ./
COPY app/Jobs/ ./app/Jobs/   

# Instala dependências + nodemon para "ouvir" as mudanças
RUN npm install -g nodemon && npm install

# Comando padrão ao iniciar o container
ENTRYPOINT ["nodemon", "./worker", "do-task-queue", "3"]